name: myIBM Cloud Auto Restart

on:
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]
  schedule:
    # - cron: '0 18 * * *'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install CF CLI
      run: |
        curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github&version=v6" | tar -zx
        sudo mv cf /usr/local/bin
      
    - name: Login CF
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT }}
      run: |
        cf l -a https://api.us-south.cf.cloud.ibm.com login  << EOF
        $IBM_ACCOUNT
        EOF
      
    - name: Restart CF APP
      run: cf rs ${{ secrets.IBM_APP_NAME }}
